environments:
  production:
    values:
      - domain: 35.246.104.142.nip.io
      - issuer: letsencrypt-production

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: harbor
    url: https://helm.goharbor.io

releases:

  - name: nginx-ingress
    namespace: nginx-ingress
    chart: stable/nginx-ingress
    version: 1.11.1

  - name: cert-manager
    namespace: cert-manager
    hooks:
      - events:
          - presync
        showlogs: true
        command: kubectl
        args:
          - label
          - namespace
          - cert-manager
          - certmanager.k8s.io/disable-validation="true"
      - events:
          - presync
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - --validate=false
          - https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager-legacy.crds.yaml
      - events:
          - presync
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - --validate=false
          - https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager-legacy.yaml
      - events:
          - presync
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - ../cert-manager/clusterissuer-letsencrypt-{{ .Environment.Name }}.yaml

  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: 1.3.2
    values:
        - ../harbor/values.yaml
