apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    run: app
spec:
  containers:
  - name: web
    image: fuckir89/otus-web:1.0
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: web-init
    image: busybox:latest
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  